be15-fin-project/be15-fin-DAO-Momentum-FE

- src/main.js
closes #000
---
📌 개요
초기 설정에서 삭제되지 않은 import 제거
🔨 주요 변경 사항
초기 설정에서 삭제되지 않은 import  제거
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> init : 초기 설정에서 삭제되지 않은 import 제거

- src/assets/css/index.css
- src/components/common/sidebar.vue
closes #000
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> Init : 사이드바 및 스크롤 css 수정

- src/features/approvals/views/ApprovalList.vue
closes #000
---
📌 개요
결재 전체 목록 조회
🔨 주요 변경 사항
- 결재 전체 목록 조회 View 생성
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> feat : 결재 전체 목록 조회

- .env
closes #000
---
📌 개요
url 경로를 위한 env 파일
🔨 주요 변경 사항
- url 경로를 위한 env 파일
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> init : url 경로를 위한 env 파일

- package-lock.json
- package.json
- src/api/axios.js
- src/assets/css/color-style.css
- src/components/common/BaseTable.vue
- src/components/common/Filter.vue
- src/components/common/FormSection.vue
- src/components/common/HeaderWithTabs.vue
- src/components/common/Pagenation.vue
- src/components/common/SideModal.vue
- src/components/common/Sidebar.vue
- src/features/performance/api.js
- src/features/performance/router.js
- src/features/performance/views/KpiDashboardView.vue
- src/main.js
- src/router/index.js
closes #000
---
📌 개요
🔨 주요 변경 사항
**KPI 분석 페이지 구현**
- 통계 표 구현
- 필터 구현
- 표 구현
- 페이지네이션 구현
- 사이드 모달 구현
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> feat: KPI 분석 페이지 하드코딩 구현

- package-lock.json
- package.json
- src/api/axios.js
- src/components/common/Sidebar.vue
- src/features/common/api.js
- src/features/common/components/LoginVisualSection.vue
- src/features/common/router.js
- src/features/common/views/LoginView.vue
- src/main.js
- src/router/index.js
- src/stores/auth.js
closes #80 
---
📌 개요
-  로그인 페이지 구현, 리프레시, 로그아웃 기능 구현
🔨 주요 변경 사항
- 로그인 페이지 구현
- / (루트 페이지) 이동 시 권한이 없다면 로그인 페이지로 이동하도록 설정
- pinia 라이브러리 추가
- authStore 구현
- 사이드바 <script> -> <script setup> 으로 변경 (pinia 때문에)
- main.js bootstrap 함수로 실행되도록 변경 (pinia 때문에)
✅ 리뷰 요청 사항
- 페이지 확인
⭐ 관련 이슈
#80
> feat: 로그인 페이지 구현, 리프레시, 로그아웃 기능 구현

- src/components/common/Sidebar.vue
closes #000
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> init : 사이드바 이동 href에서 router로 변경

- src/assets/css/color-style.css
- src/components/common/Filter.vue
- src/features/performance/views/MyKpiView.vue
closes #000
---
📌 개요
🔨 주요 변경 사항
- 필터 탭 추가 
- 드롭박스 선택 영역 표시 
- text 엔터 저장
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> init : 필터 탭 추가, text 저장, 선택 드롭박스 표시

- src/assets/css/color-style.css
- src/components/common/BaseButton.vue
- src/components/common/FieldRenderer.vue
- src/components/common/SideModal.vue
- src/components/common/Sidebar.vue
- src/features/performance/api.js
- src/features/performance/views/KpiDashboardView.vue
- src/features/performance/views/KpiEmployeeDetailView.vue
- src/features/performance/views/MyKpiView.vue
closes #35 
closes #36 
closes #37 
closes #38 
closes #98 
closes #96
closes #26
closes #34
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> feat : 자신의 KPi 목록 조회

- src/assets/css/login.css
- src/features/common/views/LoginView.vue
- src/router/index.js
📌 개요
- 로그인 페이지 변경 및 권한에 따른 페이지 접근 여부 추가
🔨 주요 변경 사항
- 로그인 페이지 수정
- 로그인 페이지에 디폴트 계정 나오도록 추가
- 권한에 따른 메인 페이지 접근 처리 추가 
✅ 리뷰 요청 사항
- 화면 확인
⭐ 관련 이슈
#80
> refactor:로그인 페이지 변경 및 권한에 따른 페이지 접근 여부 추가

- src/features/performance/api.js
- src/features/performance/router.js
- src/features/performance/views/EvaluationSelfView.vue
closes #47 
closes #48 
closes #49
---
📌 개요
🔨 주요 변경 사항
- 자가진단 목록 조회
- 자가 진단 상세 조회
- 사원 간 평가 엑셀 다운로드
- 조직 평가 엑셀 다운로드
- 자가 진단 엑셀 다운로드
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> feat : 자가 진단 목록 조회 및 상세 조회 구현, 엑셀 다운로드 구현

- .env
- package-lock.json
- package.json
- src/App.vue
- src/api/attachAuthInterceptor.js
- src/api/axios.js
- src/api/notificationApi.js
- src/components/common/AlertPanel.vue
- src/components/common/Sidebar.vue
- src/main.js
- src/stores/auth.js
- src/stores/notification.js
closes #92 
---
📌 개요
결재 알림 기능 구현
🔨 주요 변경 사항
- 결재 생성 시 첫번째 단계 결재자들에게 알림 발송
- 단계별 승인 완료시 다음 단계 결재자들에게 알림 발송
- 반려시 기안자에게 알림 발송
> feat: 결재 알림 기능 구현

- src/components/common/Filter.vue
- src/components/common/Sidebar.vue
- src/features/employee/api.js
- src/features/employee/router.js
- src/features/employee/views/ContractListView.vue
closes #000
---
📌 개요
- 계약서 목록 조회, 다운로드 기능 구현 (등록 기능은 추가 작업 필요)
🔨 주요 변경 사항
- api, 뷰, router 작성
- filter 및 sidebar 변경
- filter: 필터 항목에 객체가 매핑될 때, 원하는 텍스트 가져올 수 있도록 수정 (기존 수정과 동일한 맥락)
✅ 리뷰 요청 사항
하단의 TODO 리스트 제외하면 문제 없는 지
TODO
1. 사원 ID 부분은 트리 구조 타고 사원 선택하는 방향으로 구현
2. 파일 업로드 관련 로직 및 form 작성
- SideModal 컴포넌트 수정이 필요할 수 있음. 혹은 SideModal 물려 받는 컴포넌트 만들어서 따로 구현?
⭐ 관련 이슈
#22
> feat: 계약서 목록 조회, 다운로드 기능 구현

- package-lock.json
- src/components/common/Sidebar.vue
- src/features/employee/api.js
- src/features/employee/router.js
- src/features/employee/views/AppointListView.vue
closes #000
---
📌 개요
- 인사 발령 내역 조회 및 등록 기능 구현
🔨 주요 변경 사항
- router, api, 뷰 추가, sidebar 수정
✅ 리뷰 요청 사항
TODO
- 사원 ID 선택을 트리 구조로 수정 (FieldRenderer 컴포넌트에 추가 후 함께 반영)
- 하드코딩 된 부서 조회 수정
- 프론트 예외 처리 로직 추가 및 토스트 알림 추가
⭐ 관련 이슈
#21
> feat: 인사 발령 내역 조회 및 등록 기능 구현

- src/components/common/Sidebar.vue
- src/features/performance/api.js
- src/features/performance/router.js
- src/features/performance/views/EvaluationOrgView.vue
- src/features/performance/views/EvaluationPeerView.vue
- src/features/performance/views/EvaluationSelfView.vue
- src/features/performance/views/MyHrEvaluationView.vue
- src/features/performance/views/MyHrObjectionListView.vue
closes #60
---
📌 개요
🔨 주요 변경 사항
- 이의 제기 내역 조회 기능 구현
- 인사 평가 상세 조회 가중치 등급 표시
- 필터에 회차 추가
- 사이드바 css 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#59
> feat :  이의 제기 내역 조회 기능 구현

- src/features/approvals/components/SentApproval.vue
- src/features/approvals/components/approveType/CancelForm.vue
closes #2 #4
---
📌 개요
잘못 작성된 주석과 import 수정
🔨 주요 변경 사항
- `SenApproval`에서 주석 오타 수정
- `CancelForm`에서 잘못 import된 부분 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#2 #4
> refactor : 잘못 작성된 주석과 import 수정

- src/components/common/Sidebar.vue
📌 개요
- 상대 경로로 인한 페이지 라우팅 문제 수정
🔨 주요 변경 사항
- 모든 hrefs 경로를 절대 경로로 변경
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> [fix] 사이드바 수정

- src/components/common/BaseTable.vue
- src/features/approvals/components/ApprovalSideSection.vue
- src/features/approvals/components/FormSection.vue
- src/features/approvals/components/approveType/BusinessTripForm.vue
- src/features/approvals/components/approveType/CancelForm.vue
- src/features/approvals/components/approveType/OvertimeForm.vue
- src/features/approvals/components/approveType/ProposalForm.vue
- src/features/approvals/components/approveType/ReceiptForm.vue
- src/features/approvals/components/approveType/RemoteWorkForm.vue
- src/features/approvals/components/approveType/VacationForm.vue
- src/features/approvals/components/approveType/WorkCorrectionForm.vue
- src/features/approvals/views/ApprovalDetail.vue
- src/features/approvals/views/ApprovalList.vue
closes #6 
---
📌 개요
결재 문서 조회 시 첨부파일 조회 추가 및 css 수정
🔨 주요 변경 사항
- `BaseTable` 에서 상태 색상 변경 
- 결재 문서 상세 조회 관련된 모든 View와 Component에서 css 수정 (색상을 팔레트에 설정된 색상으로 변경)
- 각 파일 별로 알아 보기 쉽게 주석 추가
✅ 리뷰 요청 사항
⭐ 관련 이슈
#6
> refactor :  첨부파일 조회 추가 및 css 수정

- src/features/common/components/InitialPasswordSetupForm.vue
- src/features/common/components/PasswordResetForm.vue
- src/features/common/router.js
- src/features/common/views/ForgotPasswordView.vue
- src/features/common/views/InitialPasswordView.vue
- src/router/index.js
📌 개요
- 비밀번호 재설정페이지 컴포넌트화, 비밀번호 초기화 페이지 구현, 라우터 설정 변경
🔨 주요 변경 사항
- 비밀번호 찾기 페이지 라우팅 설정 변경
- 비밀번호 재설정 페이지  컴포넌트화
- 비밀번호 페이지 구현
✅ 리뷰 요청 사항
- 화면 확인
⭐ 관련 이슈
> refactor: 비밀번호 재설정페이지 컴포넌트화, 비밀번호 초기화 페이지 구현, 라우터 설정 변경

- src/components/common/CommonModal.vue
- src/components/common/Sidebar.vue
- src/features/works/components/AttendanceCard.vue
- src/features/works/components/AttendanceModal.vue
- src/features/works/components/CalendarAttendanceModal.vue
closes #000
---
📌 개요
🔨 주요 변경 사항
- 근태를 위한 컴포넌트 생성
- 근태 모달 수정
- 기본 모달 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> refactor : 근태 모달 및 캘린더 근태 조회 모달 수정

- src/components/common/BaseTable.vue
- src/components/common/SideModal.vue
- src/components/common/Sidebar.vue
- src/components/common/form/FieldRenderer.vue
- src/features/employee/api.js
- src/features/employee/views/ContractListView.vue
- src/features/mypage/router.js
- src/features/mypage/views/MyContractsView.vue
closes #000
---
📌 개요
- 본인 계약서 조회 기능 구현
- 관리자 계약서 조회, 등록, 삭제 기능 구현
🔨 주요 변경 사항
- MyContractsView 추가 및 라우터 설정
- ContractListView 수정
- 컴포넌트 BaseTable: 버튼 2개 받을 수 있도록 수정
- 컴포넌트 SideModal, FieldRenderer: 파일 받을 수 있도록 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#22
> feat: 본인 계약서 조회, 관리자 계약서 조회, 등록, 삭제 기능 구현

- src/components/common/form/DeptList.vue
- src/components/common/form/FieldRenderer.vue
- src/features/company/components/DepartmentInfoCard.vue
- src/features/company/views/OrgChartView.vue
- src/features/settings/api.js
- src/features/settings/router.js
- src/features/settings/views/CompanyForm.vue
- src/features/settings/views/DepartmentForm.vue
- src/features/settings/views/SettingView.vue
📌 개요
- 부서 설정 페이지 구현
🔨 주요 변경 사항
- 부서 설정 페이지 구현
- 사이드바 부서 선택 컴포넌트 추가
- 설정 페이지 리팩토링
- 
✅ 리뷰 요청 사항
- 화면 확인
⭐ 관련 이슈
#
> 부서 설정 페이지 구현

- src/components/common/BaseTable.vue
- src/components/common/form/FieldRenderer.vue
- src/features/employee/views/AppointListView.vue
- src/features/employee/views/ContractListView.vue
- src/features/employee/views/EmployeeListView.vue
- src/features/mypage/views/MyContractsView.vue
- src/features/works/views/WorkListView.vue
closes #22, #21
---
📌 개요
- 목록 조회 페이지들 수정 (사원 및 부서 트리 선택 드롭다운)
🔨 주요 변경 사항
- 배지 추가 (근무 유형, 재직 상태 등)
- BaseTable 컴포넌트 수정
- FileRenderer 오류 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#23, #18, #22, #21
> feat: 목록 조회 페이지 수정 (FileRenderer fix 포함)

- src/features/approvals/api.js
- src/features/approvals/components/ApprovalSideSection.vue
- src/features/approvals/components/EmployeeModal.vue
- src/features/approvals/components/FormSection.vue
- src/features/approvals/components/WriteFormSection.vue
- src/features/approvals/components/approveType/BusinessTripForm.vue
- src/features/approvals/components/approveType/OvertimeForm.vue
- src/features/approvals/components/approveType/ProposalForm.vue
- src/features/approvals/components/approveType/ReceiptForm.vue
- src/features/approvals/components/approveType/VacationForm.vue
- src/features/approvals/router.js
- src/features/approvals/views/ApprovalList.vue
- src/features/approvals/views/ApproveEditCreateView.vue
closes #000
(api까지 완벽하게 연동되면 닫을 예정입니다.)
---
📌 개요
결재 문서 작성 기능 
🔨 주요 변경 사항
- 결재 문서 작성 view 생성
- 결재 문서 종류 별로 detail 안에 문서를 작성할 수 있는 기능을 추가해서 작성 
- 결재 문서 작성 관련 api 연결 (결재 문서 작성 api, ocr api, 상사 불러오는 api)
- router 설정 완료
- 결재 문서 작성 시 결재선과 참조선 설정을 위한 modal 구성 완료
- 결재 문서 작성에서 side와 form 구분해 작성 완료
✅ 리뷰 요청 사항
- 현재 모든 문서가 다 제대로 작성되는 상황이 아님 : 계속 수정해야 함 (우선 화면 구성이 이렇다는 정도를 보여주기 위해 올림)
⭐ 관련 이슈
#5
> feat : 결재 문서 작성 기능

- src/features/performance/views/KpiDashboardView.vue
- src/features/performance/views/KpiEmployeeDetailView.vue
- src/features/retention-support/components/DeptStabilityBar.vue
- src/features/retention-support/components/StabilityDonut.vue
- src/features/retention-support/views/ProspectEmployeeListView.vue
- src/features/retention-support/views/RetentionRoundView.vue
closes #000
---
📌 개요
🔨 주요 변경 사항
- KPI 상세 조회 에러 수정
- 근속 전망 테이블 정보 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> refactor : KPI 상세 조회 수정 및 근속 전망 목록 정보 수정

- src/features/settings/api.js
- src/features/settings/router.js
- src/features/settings/views/CompanyForm.vue
- src/features/settings/views/DepartmentForm.vue
- src/features/settings/views/PositionForm.vue
- src/features/settings/views/SettingView.vue
closes #107 
---
📌 개요
- 직위 정보 설정 페이지 구현
🔨 주요 변경 사항
- 직위 정보 설정 페이지 구현
- 직위 조회, 수정, 삭제 기능 구현
✅ 리뷰 요청 사항
- 화면 확인
⭐ 관련 이슈
#107
> [feat #107] 직위 정보 설정 페이지 구현

- src/components/common/form/FieldRenderer.vue
- src/components/common/form/ScoreBarChart.vue
- src/features/mypage/components/profile/SectionHeader.vue
- src/features/performance/views/HrObjectionRequestView.vue
- src/features/performance/views/SubmitEvaluationTasks.vue
closes #000
---
📌 개요
🔨 주요 변경 사항
- 프로필 아이콘 색상 수정
- 평가 제출 로직 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> refactor : 아이콘 색수정 및 평가 제출 로직 수정

- src/features/employee/views/AppointListView.vue
closes #000
---
📌 개요
- 발령 등록 UX/UI 개선
🔨 주요 변경 사항
- 승진 선택 시 부서 및 직위 자동 배정
- 부서 선택 트리 드롭다운 수정 (사원 선택과 통일성 있도록 컴포넌트화된 deptList 사용
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> refactor: 발령 등록 UX/UI 개선

- src/components/common/form/FieldRenderer.vue
- src/features/employee/views/EmployeeListView.vue
closes #000
---
📌 개요
- 사원 등록 UX/UI 개선
🔨 주요 변경 사항
- 입사일에 기본값 부여 (등록일)
- 입사일에 따라 부여 휴가 시간 자동 반영 (필요 시 수정은 가능하게 열어둠)
- 권한 설정 부분 임시 주석 처리
- 사원 등록 완료 후 모달 다시 열 때, request 객체 초기화
- FieldRenderer에서 불필요한 부분 삭제 (부서 트리 드롭다운에 사용하던 'tree'는 'deptList'로 통일)
✅ 리뷰 요청 사항
⭐ 관련 이슈
#18
> refactor: 사원 등록 UX/UI 개선

- src/components/common/form/SliderGroup.vue
- src/features/performance/views/EvaluationRoundView.vue
- src/features/performance/views/SubmitEvaluationTasks.vue
- src/features/retention-support/components/StabilityDonut.vue
closes #000
---
📌 개요
🔨 주요 변경 사항
- 근속 전망 대시보드 통계 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> refactor : 안전성 비율 API 수정에 따른 페이지 수정

- src/assets/css/color-style.css
- src/components/common/form/FieldRenderer.vue
- src/components/common/form/FormNotice.vue
- src/components/common/form/ProgressTimeline.vue
- src/components/common/form/RetentionScoreCard.vue
- src/features/performance/views/SubmitEvaluationTasks.vue
- src/features/retention-support/components/StabilityDonut.vue
- src/features/retention-support/views/ProspectEmployeeListView.vue
closes #000
---
📌 개요
🔨 주요 변경 사항
- KPI 진척 기준 css 수정
- 근속 전망 점수 css 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> refactor : 전반적인 css 수정 

- src/components/common/Sidebar.vue
closes #000
---
📌 개요
- 사이드바 활성화 조건 수정
🔨 주요 변경 사항
- 사원 상세 조회(=관리자의 프로필 조회) 시 '사원 목록 조회' 탭이 활성화되도록 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> refactor: 사이드바 수정

- src/features/employee/views/CSVUploadView.vue
- src/features/employee/views/EmployeeListView.vue
closes #000
---
📌 개요
- 사원 CSV 일괄 등록 페이지 수정
🔨 주요 변경 사항
- 입력 값에 사번 삭제
- CSV 등록 완료 후 목록 조회로 라우팅 추가
- 폼 등록 시 권한 필드 삭제
✅ 리뷰 요청 사항
- TODO: 다운로드할 CSV 양식 파일 수정 필요 (오후 작업 예정)
⭐ 관련 이슈
#19, #18
> refactor: 사원 CSV 일괄 등록 페이지 수정

- src/features/performance/views/EvaluationOrgView.vue
- src/features/performance/views/HrObjectionListView.vue
- src/features/performance/views/HrObjectionRequestView.vue
- src/features/performance/views/KpiEmployeeListView.vue
- src/features/performance/views/MyHrEvaluationView.vue
- src/features/performance/views/MyKpiView.vue
closes #000
---
📌 개요
🔨 주요 변경 사항
- 오타 수정
- 이의제기의 취소 필터 추가
- 이의제기 승인 반려 시 처리 사유 빈값으로 들어가는 문제 수정
- KPI 필터, 테이블 정보 수정 및 css 약소 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> refactor : 필터 및 모달 일부 수정

- src/components/common/Filter.vue
- src/components/common/Sidebar.vue
- src/features/settings/api.js
- src/features/settings/router.js
- src/features/settings/views/HoolidayForm.vue
- src/features/settings/views/SettingView.vue
closes #110 
---
📌 개요
- 휴일 관리 페이지 구현
🔨 주요 변경 사항
- 휴일 관리 페이지
- 휴일 조회 기능 구현
- 휴일 등록 기능 구현
- 휴일 삭제 기능 구현
- filter에 연,월 입력 가능한 필터 추가
✅ 리뷰 요청 사항
- 화면 구성 확인
⭐ 관련 이슈
#110
> feat: 휴일 관리 페이지 구현

- src/components/common/SideModal.vue
- src/components/common/form/MemberPickerField.vue
- src/features/retention-support/api.js
- src/features/retention-support/components/OrgTree.vue
- src/features/retention-support/views/ContactRecordView.vue
- src/features/retention-support/views/ProspectEmployeeListView.vue
closes #197
---
📌 개요
🔨 주요 변경 사항
- 근속 전망 상세 조회 페이지에 면담 요청 버튼 추가
- 해당 버튼을 통해 면담 요청 상세 모달로 이동 및 부서와 사원 자동 선택
- 상급자가 없는 경우 예외처리
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> feat : 근속 전망 상세 조회에서 면담 요청 진행

- src/features/mypage/views/EmployeeProfileView.vue
📌 개요
- 내 정보 조회 페이지 스타일 수정
🔨 주요 변경 사항
- 헤더 스타일 변경
✅ 리뷰 요청 사항
- 화면 구성 확인
⭐ 관련 이슈
#
> style: 내 정보 조회 페이지 스타일 수정

- src/features/employee/views/AdminEmployeeProfileView.vue
closes #000
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> [style] 사원 프로필 조회 css 수정

- src/features/company/components/DepartmentInfoCard.vue
- src/features/company/views/CompanyInfoView.vue
- src/features/company/views/OrgChartView.vue
📌 개요
- 회사 정보, 조직도 css 수정
🔨 주요 변경 사항
- 회사 정보 페이지 :  좌우 패딩값 추가
- 조직도 페이지 : 좌우 패딩값 추가, 애니메이션 추가
✅ 리뷰 요청 사항
- 화면 확인
⭐ 관련 이슈
#
> style: 회사 정보, 조직도 css 수정

- src/assets/css/index.css
- src/assets/css/login.css
- src/components/common/Sidebar.vue
- src/components/layout/LayoutDefault.vue
closes #000
---
📌 개요
🔨 주요 변경 사항
- 전체 크기에서 80 % 축소
- 컨텐트 높이의 100vh를 100%로 변경
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> refactor : 전체적인 크리 80% 축소

- src/components/common/Pagination.vue
- src/components/common/SideModal.vue
closes #000
---
📌 개요
🔨 주요 변경 사항
- 사이드 모달 CSS 수정 ( 높이 문제 수정 )
- 페이지네이션 slider-track 위치 함수 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> refactor : 사이드 모달 및 페이지네이션  css 수정

- src/features/employee/components/profile/HistoryInfoEditable.vue
- src/features/employee/views/AdminEmployeeProfileView.vue
closes #000
---
📌 개요
- 인사 정보 수정 기능에 대한 버그 수정
🔨 주요 변경 사항
- 수정 도중 취소 버튼을 눌렀을 때, 수정 시도하던 기록이 남던 문제 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> [fix] 인사 정보 수정 기능

- src/components/common/CommonModal.vue
- src/features/performance/components/DonutChart.vue
- src/features/performance/components/LineChart.vue
- src/features/performance/views/KpiDashboardView.vue
- src/features/performance/views/MyKpiView.vue
closes #000
---
📌 개요
🔨 주요 변경 사항
- KPI 진행 현황 통계 조회 기준 수정 ( 기본 현재 월 )
- KPI 상태 조건 수정 - 수행중, 달성, 기한초과 등
- 통계 이름 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> refactor KPI 진행 현황 통계 수정 및 KPI 상태 조건 수정

- src/features/settings/components/CompanyBanner.vue
- src/features/settings/components/RoleOptionCard.vue
- src/features/settings/views/CompanyForm.vue
- src/features/settings/views/DepartmentForm.vue
- src/features/settings/views/RoleForm.vue
- src/features/settings/views/SettingView.vue
📌 개요
- 설정 페이지 전반적인 css 수정
🔨 주요 변경 사항
- 각 설정 페이지 padding 수정
- 애니메이션 추가
- 아이콘 색상 통일
✅ 리뷰 요청 사항
- 화면 확인
⭐ 관련 이슈
#
> style: 설정 페이지 전반적인 css 수정

- src/features/settings/views/DepartmentForm.vue
- src/features/settings/views/HoolidayForm.vue
📌 개요
- 부서 삭제 모달 변경
🔨 주요 변경 사항
- 부서 삭제 모달 toast로 변경
✅ 리뷰 요청 사항
-화면 구성 확인
⭐ 관련 이슈
#
> style: 부서 삭제 모달 변경

- src/features/announcement/views/AnnouncementCreateView.vue
- src/features/announcement/views/AnnouncementDetailView.vue
- src/features/announcement/views/AnnouncementEditView.vue
closes #000
---
📌 개요
- 공지사항 알림 수정
🔨 주요 변경 사항
- alert를 toast로 수정 (UX/UI 통일)
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> [style] 공지사항 알림 수정

- src/features/settings/views/RoleForm.vue
📌 개요
- 권한 수정 동작 수정
🔨 주요 변경 사항
- 권한 수정시 선택한 사원의 권한 조회 비활성화
✅ 리뷰 요청 사항
- 화면 확인
⭐ 관련 이슈
#
> fix: 권한 수정 동작 수정

- src/features/employee/views/AppointListView.vue
closes #000
---
📌 개요
- 인사 발령 내역 조회 페이지 수정
🔨 주요 변경 사항
- 필터 드롭다운에 정렬 기준 명시
✅ 리뷰 요청 사항
⭐ 관련 이슈
#21
> [refactor #21] 인사 발령 내역 조회 페이지 수정

- src/features/works/composable/useAttendance.js
closes #000
---
📌 개요
-  퇴근 등록 기능 수정
🔨 주요 변경 사항
- 이미 퇴근 등록을 완료한 경우 다시 등록하지 못하도록 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#17
> [refactor] 퇴근 등록 기능 수정

- src/components/common/form/FieldRenderer.vue
- src/components/common/form/RadarChart.vue
- src/components/common/form/RetentionScoreCard.vue
- src/features/retention-support/components/MetricCard.vue
- src/features/retention-support/views/ProspectDashboardView.vue
- src/features/retention-support/views/ProspectEmployeeListView.vue
closes #000
---
📌 개요
🔨 주요 변경 사항
- 근속전망 대시보드 CSS 수정
- 근속 전망 지수 툴팁 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> refactor : css 수정 및 근속 전망 지수 툴팁 수정

- src/components/common/AlertPanel.vue
- src/components/common/Filter.vue
- src/components/common/Sidebar.vue
closes #000
---
📌 개요
🔨 주요 변경 사항
- 사이드바의 회사정보를 유저 정보로 수정
- 퇴근 버튼을 프로필 이미지로 대체
- 알림 모달을 사이드바 collpsed 상태일때 위치 변경
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> refactor 사이드바 정보 수정 - 회사 정보 대신 프로필 정보 및 알림 모달 css 수정

- src/components/common/DeleteConfirmToast.vue
- src/components/common/Sidebar.vue
- src/components/common/form/FieldRenderer.vue
- src/features/employee/components/profile/HistoryInfoEditable.vue
- src/features/employee/views/AdminEmployeeProfileView.vue
- src/features/employee/views/AppointListView.vue
- src/features/employee/views/CSVUploadView.vue
- src/features/employee/views/ContractListView.vue
- src/features/employee/views/EmployeeListView.vue
- src/features/mypage/views/MyContractsView.vue
- src/features/works/views/WorkListView.vue
closes #000
---
📌 개요
- API 호출 실패 시 에러 메시지 수정
🔨 주요 변경 사항
- DeleteConfirmToast: 수정 취소 시에도 활용할 수 있도록 message props 추가 (기본값은 그대로 유지)
- 목록 조회 페이지: catch 구문 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> refactor: 토스트 알림 수정

- src/features/company/components/DepartmentInfoCard.vue
- src/features/company/views/OrgChartView.vue
📌 개요
- css 클래스명 변경 및 버튼 클릭 이벤트 위치 변경
🔨 주요 변경 사항
- 조직도 페이지 css 클래스 명 변경
- DepartmentInfoCard 수정, 삭제 버튼 이벤트 위치 변경
✅ 리뷰 요청 사항
- 화면 확인
⭐ 관련 이슈
#
> fix: css 클래스명 변경 및 버튼 클릭 이벤트 위치 변경

- src/features/common/api.js
- src/features/common/components/PasswordResetForm.vue
- src/features/common/views/ResetPasswordView.vue
📌 개요
- 비밀번호 재설정 페이지 기능 수정
🔨 주요 변경 사항
- 토큰 검사 로직 추가
✅ 리뷰 요청 사항
- 페이지 확인
⭐ 관련 이슈
#
> fix: 비밀번호 재설정 페이지 기능 수정

- src/features/works/composable/useAttendance.js
closes #000
---
📌 개요
- 출퇴근 버튼 애니메이션 수정
🔨 주요 변경 사항
- 퇴근 전 상태에 shake 효과 복구
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> style: 출퇴근 버튼 수정

- src/components/common/Chatbot.vue
- src/features/employee/views/EmployeeListView.vue
- src/features/settings/views/RoleForm.vue
closes #000
---
📌 개요
- 시스템 권한명 수정
🔨 주요 변경 사항
- 팀장 -> 부서 관리자
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> refactor: 권한명 수정

- src/features/settings/views/CompanyForm.vue
- src/features/settings/views/HoolidayForm.vue
- src/features/settings/views/PositionForm.vue
📌 개요
- 오타 수정,용어 통일 및 애니메이션 추가
🔨 주요 변경 사항
- 휴일 관리 페이지 오타 수정
- 직위 관리 페이지 용어 통일
- 회사 관리 페이지 애니메이션 추가
✅ 리뷰 요청 사항
- 화면 확인
> fix: 오타 수정,용어 통일 및 애니메이션 추가

- src/components/common/SideModal.vue
- src/components/common/form/FieldRenderer.vue
- src/features/works/composable/useAttendance.js
closes #000
---
📌 개요
- 불필요한 로그 삭제
🔨 주요 변경 사항
- console.log, console.error 삭제 또는 토스트로 대체
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> refactor: 불필요한 로그 삭제

- src/features/settings/views/RoleForm.vue
📌 개요
- 설정 페이지 불필요 로그 제거
🔨 주요 변경 사항
- 권한 관리 페이지 불필요 로그 제거
✅ 리뷰 요청 사항
- 로그 확인
⭐ 관련 이슈
#
> fix: 설정 페이지 불필요 로그 제거

- src/router/index.js
closes #000
---
📌 개요
- intro 페이지 권한 삭제
🔨 주요 변경 사항
- 로그인하지 않은 유저가 접근할 수 있도록 수정 (`src/router/index` 수정)
✅ 리뷰 요청 사항
- 혹시 추가로 수정해야 할 부분 있는 지
⭐ 관련 이슈
#
> fix: intro 페이지 권한 삭제

- src/components/common/Chatbot.vue
> refactor: 챗봇 메시지 '\n' 반영되도록 css 수정

- .github/workflows/deploy.yml
📌 개요
- github actions deploy.yml 작성
🔨 주요 변경 사항
-  deploy.yml 작성
✅ 리뷰 요청 사항
- 스크립트 확인
> docs: github actions deploy.yml 작성

- .github/workflows/deploy.yml
📌 개요
- github actions deploy 수정
🔨 주요 변경 사항
- aws url 반영
✅ 리뷰 요청 사항
- 스크립트 확인
> docs: github actions deploy 수정

- .github/workflows/deploy.yml
📌 개요
- github actions deploy,yml 수정
🔨 주요 변경 사항
- release 브랜치에서 push시 CI 실행하도록 수정
✅ 리뷰 요청 사항
- 확인
⭐ 관련 이슈
#
> docs: github actions deploy,yml 수정

- src/features/employee/views/AdminEmployeeProfileView.vue
closes #000
---
📌 개요
- 헤더 수정
🔨 주요 변경 사항
- 헤더 생성을 위한 to 경로 추가 (실제로 문제가 수정되는 지는 배포 환경 확인 필요)
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> fix: 배포 환경에서 헤더 생성되지 않는 문제 수정

- src/features/common/views/IntroView.vue
- src/features/performance/views/HrObjectionRequestView.vue
- src/features/performance/views/KpiDashboardView.vue
- src/features/performance/views/KpiEmployeeDetailView.vue
- src/features/performance/views/KpiEmployeeListView.vue
- src/features/performance/views/KpiRequestsView.vue
- src/features/performance/views/MyKpiView.vue
- src/features/retention-support/components/MetricCard.vue
- src/features/retention-support/views/ProspectEmployeeListView.vue
closes #000
---
📌 개요
🔨 주요 변경 사항
- 라우터 주소로 인한 헤더 타이틀 문제 수정
- 콘솔 로그 삭제
- 근속 전망 대시보드 카드 사이즈 줄이기
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> refactor : 조회 오류 수정 및 CSS 수정, 로그 삭제

- src/features/common/views/LoginView.vue
- src/features/company/views/OrgChartView.vue
- src/stores/auth.js
📌 개요
- console.log 제거
🔨 주요 변경 사항
- console.log 제거
✅ 리뷰 요청 사항
- 코드 확인
> fix: console.log 제거

- src/features/common/views/IntroView.vue
- src/features/retention-support/components/MetricCard.vue
- src/features/retention-support/views/RetentionRoundView.vue
closes #000
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> refactor : 소개 페이지 로그인 버튼 CSS 확정

- src/features/common/views/LoginView.vue
📌 개요
- 로그인 기본값 제거
🔨 주요 변경 사항
- 로그인 기본값 제거
✅ 리뷰 요청 사항
- 페이지 확인
⭐ 관련 이슈
#
> fix: 로그인 기본값 제거

- src/assets/css/index.css
- src/components/common/SideModal.vue
- src/features/common/views/IntroView.vue
- src/features/performance/views/KpiEmployeeDetailView.vue
- src/features/performance/views/KpiRequestsView.vue
- src/features/performance/views/MyKpiView.vue
closes #000
---
📌 개요
🔨 주요 변경 사항
- 드래그 스타일 수정
- 소개 페이지 수정
- 사이드바 스타일 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> refactor : 드래그, 소개, 사이드바 스타일 수정

- src/features/employee/components/UploadCard.vue
- src/features/employee/components/profile/HistoryInfoEditable.vue
- src/features/employee/views/AdminEmployeeProfileView.vue
- src/features/employee/views/AppointListView.vue
- src/features/employee/views/ContractListView.vue
- src/features/employee/views/EmployeeListView.vue
- src/util/toastError.js
closes #000
---
📌 개요
- 프론트엔드 검증 로직 추가
🔨 주요 변경 사항
- 요청 객체 값이 유효하지 않으면 API를 호출하지 않도록 프론트엔드 로직 작성
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> refactor: 프론트엔드 검증 로직 추가

- src/features/common/views/LoginView.vue
📌 개요
- 로그인 폼 수정
🔨 주요 변경 사항
- 이메일 입력란 placeholder 수정
✅ 리뷰 요청 사항
- 화면 확인
⭐ 관련 이슈
#
> fix: 로그인 폼 수정

- src/components/common/SideModal.vue
- src/components/common/Sidebar.vue
- src/components/common/form/MemberPickerField.vue
- src/features/mypage/components/VacationInfoCard.vue
- src/features/mypage/views/EmployeeProfileView.vue
closes #000
---
📌 개요
- 불필요한 콘솔 출력 제거
🔨 주요 변경 사항
- console.log, console.error 삭제 또는 토스트 알림으로 변경
✅ 리뷰 요청 사항
- 변경 내용 적절한지 (토스트로 전환하는 게 나은 데 삭제했거나 혹은 그 반대인 경우가 있는 지)
⭐ 관련 이슈
#
> refactor: console 출력 제거

- src/features/common/components/PasswordResetForm.vue
- src/features/company/views/CompanyInfoView.vue
- src/features/company/views/OrgChartView.vue
📌 개요
- console 메세지 처리 변경
🔨 주요 변경 사항
- 비밀번호 변경, 회사 정보, 조직도 페이지 console 처리 변경
✅ 리뷰 요청 사항
- 코드 확인
> fix: console 메세지 처리 변경

- src/components/common/Sidebar.vue
- src/features/retention-support/views/ContactRecordView.vue
- src/features/retention-support/views/MyRetentionContactView.vue
closes #000
---
📌 개요
🔨 주요 변경 사항
- 팀장인 경우 면담 요청 내역 조회 가능
- 인사 담당자 혹은 최고 관리자인 경우 면담 내역 조회 가능
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> refactor : 권한별 면담 내역 및 면담 요청 내역 조회 변경

- src/components/common/Chatbot.vue
📌 개요
chore: RAG 참조 문서에 맞게 용어 수정(부서 관리자 -> 팀장)
> chore: RAG 참조 문서에 맞게 용어 수정(부서 관리자 -> 팀장)
